# Generated by Django 2.0 on 2020-01-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='CANDIDATO')),
                ('type', models.TextField(choices=[('PRESIDENCIA', 'PRESIDENCIA'), ('CANDIDATO', 'CANDIDATO')], default='CANDIDATO')),
                ('born_area', models.TextField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')], default='AB')),
                ('current_area', models.TextField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')], default='AB')),
                ('primaries', models.BooleanField(default=False)),
                ('sex', models.TextField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='end_date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='start_date_selected',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidatesGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.CandidatesGroup'),
        ),
        migrations.AddField(
            model_name='voting',
            name='candidatures',
            field=models.ManyToManyField(related_name='voting', to='voting.CandidatesGroup'),
        ),
    ]
