# Generated by Django 2.0 on 2019-12-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, choices=[('PRESIDENCIA', 'PRESIDENCIA'), ('CANDIDATO', 'CANDIDATO')], null=True)),
                ('born_area', models.TextField(blank=True, null=True)),
                ('current_area', models.TextField(blank=True, null=True)),
                ('primaries', models.BooleanField(default=False)),
                ('sex', models.TextField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidatesGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.CandidatesGroup'),
        ),
    ]
