# Generated by Django 2.0 on 2020-01-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20191206_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='candidatures',
            field=models.ManyToManyField(related_name='voting', to='voting.CandidatesGroup'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidatesGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.CandidatesGroup'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
