# Generated by Django 2.0 on 2019-12-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20191206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='born_area',
            field=models.TextField(blank=True, choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_area',
            field=models.TextField(blank=True, choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')]),
        ),
    ]
