# Generated by Django 2.0 on 2020-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20200105_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date_selected',
            field=models.DateTimeField(null=True),
        ),
    ]
