# Generated by Django 2.0 on 2019-12-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20191228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='type',
            field=models.TextField(choices=[('PRESIDENCIA', 'PRESIDENCIA'), ('CANDIDATO', 'CANDIDATO')], default='PRESIDENCIA'),
        ),
    ]
