# Generated by Django 2.0 on 2020-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20191229_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
