# Generated by Django 2.0 on 2020-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_voting_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
