# Generated by Django 2.0 on 2020-01-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20200105_1637'),
        ('voting', '0007_auto_20200105_1452'),
    ]

    operations = [
    ]
