# Generated by Django 2.0 on 2020-01-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_merge_20200110_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='candidatures',
            field=models.ManyToManyField(related_name='voting', to='voting.CandidatesGroup'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidatesGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.CandidatesGroup'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sex',
            field=models.TextField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
