# Generated by Django 2.0 on 2020-01-10 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profileS',
            new_name='profile',
        ),
    ]
