# Generated by Django 2.0 on 2020-01-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20200110_1937'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_profile',
        ),
    ]
